Feature/product detail#1
potepancamp/youhei_kawaguchi pull request #2
Opened 2021-07-16 02:32 UTC by youhei0204

課題2 商品詳細ページを実装しました。

issue:
[課題2]商品詳細ページを実装 #1

2021-07-16 04:24 UTC, masanarih0ri reviewed
いくつかコメントしました。テストもないようだったのでそちらも追加お願いします。

2021-07-19 13:51 UTC, nakanoTaku commented on app/views/layouts/_product_quick_view_modal.erb
> +                <!-- <option value="0">数</option> -->
コメントアウトする場合は必ず理由を書きましょう。不要な場合は削除しましょう。

2021-07-19 14:09 UTC, nakanoTaku commented on app/views/layouts/_header.html.erb
> +              <!-- <span><a data-toggle="modal" href='.login-modal'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span> -->
コメントアウトは削除しましょう！

2021-07-19 14:14 UTC, nakanoTaku commented
レビュアーの中野です。
コメントしましたので、ご確認お願いします。

2021-07-20 01:29 UTC, youhei0204 commented
中野さん
川口です。ご指摘ありがとうございました。

2021-07-20 01:40 UTC, youhei0204 commented on app/views/layouts/_header.html.erb
> +              <!-- <span><a data-toggle="modal" href='.login-modal'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span> -->
こちら修正しました。

2021-07-20 01:40 UTC, youhei0204 commented on app/helpers/application_helper.rb
> +      'BIGBAG Store'
こちら修正しました。

2021-07-20 02:37 UTC, hyo0306 reviewed
おつかれさまです！インラインでコメントしたので確認お願いします。また下記も確認お願いします↓

1. こちら対応されていないようです。しっかり確認・対応しましょう。
https://github.com/potepancamp/youhei_kawaguchi/pull/2#issuecomment-882008283

2. 
> ＜レビュアーからのコメント＞で「こちらマージの向け先はmasterではないでしょうか？」というコメントをいただいたのですが、Gitflowのワークフローに従ってdevelopから分岐したfeatureブランチにて開発しているため、向け先はdevelopで問題ない認識です。（因みにmasterとdevelopに差分はありません）

ポテパンでは基本的にmasterに直接マージをしていくフローです（カリキュラムにもmasterに直接pushしない、など書いてありますね）。developブランチにpushしていくワークフローなら、clone時点で既にdevelopブランチが存在していたはずです。どのワークフローを導入するかは実装者が決めることではなく、そのプロジェクトの方針に従うのが通例です。

差分がないということなので、masterにしておきましょう。

2021-07-20 02:37 UTC, hyo0306 commented on app/views/layouts/application.html.erb
> +  <%= javascript_include_tag 'application' %>
jsの読み込みに時間がかかるとページ読み込みがブロックされるので、bodyの最後に記述しましょう。

2021-07-20 02:37 UTC, hyo0306 commented on app/controllers/potepan/sample_controller.rb
> +      @images = @product.gallery.images.where(viewable_id: @product.master.id)
masterの画像だけ取り出すためにこのコードを書いているなら、ちょっと冗長だと思います。masterの画像だけ取り出せるメソッドは既にありませんか？確認してみてください。

2021-07-20 02:37 UTC, hyo0306 commented on app/views/layouts/_footer.html.erb
> +        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
👍

2021-07-20 02:37 UTC, hyo0306 commented on app/views/potepan/sample/products.html.erb
> +                    <%= image_tag(image.try(:url) ) %>
画像のサイズを考慮してください
他の同様な箇所も見直してください

2021-07-20 02:37 UTC, hyo0306 commented on app/views/potepan/sample/products.html.erb
> +            <h3><%= @product.display_price.to_html %></h3>
to_htmlしている理由はなんですか？不必要かなと思いました

2021-07-20 02:37 UTC, hyo0306 commented on config/initializers/assets.rb
> +    env.export_concurrent = false
インデントズレてませんか？

2021-07-20 02:37 UTC, hyo0306 commented on spec/views/potepan/products.html.erb_spec.rb
> +    Spree::Product.create!(
Spreeのテストデータを使用しましょう

2021-07-20 02:37 UTC, hyo0306 commented on spec/views/potepan/products.html.erb_spec.rb
> +    product1 = Spree::Product.find_by(name: 'test_product1')
factory botなどを使ってfind_byせずに参照できるようにしましょう
他の箇所も同様に修正してください

2021-07-20 02:37 UTC, hyo0306 commented on spec/views/potepan/products.html.erb_spec.rb
> +    visit "/potepan/products/#{product1.id}"
prefix_pathを使ってください
他の箇所も同様に修正してください

2021-07-20 02:37 UTC, hyo0306 commented on spec/views/potepan/products.html.erb_spec.rb
> +RSpec.feature 'Get /potepan/products/:id' do
このファイル全体で行っているのはユーザ側動作のテスト（E2Eテスト）です。views_specで行うテストではないのでfeature_spec or system_specに変更してください。

2021-07-20 02:37 UTC, hyo0306 commented on spec/views/potepan/products.html.erb_spec.rb
> +RSpec.feature 'Get /potepan/products/:id' do
ファイル名も修正しましょう

2021-07-20 02:37 UTC, hyo0306 commented on spec/views/potepan/products.html.erb_spec.rb
> +    expect(page).not_to have_selector '.media-body', text: product2.name
ある商品のidを1つだけ指定してアクセスできるページなので、product1の表示だけ確認できればOKだと思います。

2021-07-20 02:37 UTC, hyo0306 commented on spec/views/potepan/products.html.erb_spec.rb
> +    page.all('a', text: 'HOME').each do |link|
eachだと最後の結果だけが評価されるのでここでは適切ではなさそうです。テスト内で繰り返す場合はallを使いましょう（しっかり調べた上で使いましょう）

2021-07-21 08:04 UTC, youhei0204 commented
hyoさん
細かく見ていただきありがとうございます。

2021-07-21 08:49 UTC, youhei0204 commented on .rubocop_todo.yml
> +# versions of RuboCop, may require this file to be generated again.
こちら削除しました。

2021-07-21 08:49 UTC, youhei0204 commented on spec/views/potepan/products.html.erb_spec.rb
> +    page.all('a', text: 'HOME').each do |link|
こちら修正しました。

2021-07-21 08:50 UTC, youhei0204 commented on spec/views/potepan/products.html.erb_spec.rb
> +    expect(page).not_to have_selector '.media-body', text: product2.name
こちら修正しました。

2021-07-21 08:50 UTC, youhei0204 commented on spec/views/potepan/products.html.erb_spec.rb
> +RSpec.feature 'Get /potepan/products/:id' do
こちら修正しました。

2021-07-21 08:50 UTC, youhei0204 commented on spec/views/potepan/products.html.erb_spec.rb
> +    visit "/potepan/products/#{product1.id}"
こちら修正しました。

2021-07-21 08:50 UTC, youhei0204 commented on spec/views/potepan/products.html.erb_spec.rb
> +    product1 = Spree::Product.find_by(name: 'test_product1')
こちら修正しました。

2021-07-21 08:50 UTC, youhei0204 commented on app/views/potepan/sample/products.html.erb
> +                    <%= image_tag(image.try(:url) ) %>
こちら修正しました。

2021-07-21 08:50 UTC, youhei0204 commented on app/views/potepan/sample/products.html.erb
> +            <h3><%= @product.display_price.to_html %></h3>
こちら削除しました。

2021-07-21 08:50 UTC, youhei0204 commented on config/initializers/assets.rb
> +    env.export_concurrent = false
ずれてました。修正しました。

2021-07-21 08:51 UTC, youhei0204 commented on spec/views/potepan/products.html.erb_spec.rb
> +    Spree::Product.create!(
こちら修正しました。

2021-07-21 08:51 UTC, youhei0204 commented on app/controllers/potepan/sample_controller.rb
> +      @images = @product.gallery.images.where(viewable_id: @product.master.id)
こちらスマートにしました。

2021-07-21 08:51 UTC, youhei0204 commented on app/views/layouts/application.html.erb
> +  <%= javascript_include_tag 'application' %>
こちら修正しました。

2021-07-21 08:51 UTC, youhei0204 commented on config/routes.rb
> +    get 'products/:id',             to: 'sample#products'
こちら修正しました。

2021-07-21 08:53 UTC, youhei0204 commented
ご指摘いただいた箇所を全て修正しました。
また、PR先をdevelop -> masterに変更し、request spec,helper specを追加しています。

2021-07-21 11:53 UTC, shimizu-yuta reviewed
レビュアーの清水です。
コメントしましたのでご確認ください。

2021-07-21 11:53 UTC, shimizu-yuta commented on app/controllers/potepan/products_controller.rb
> +      # issue#1
コメント不要です。

2021-07-21 11:53 UTC, shimizu-yuta commented on app/controllers/potepan/products_controller.rb
> +      @images = @product.master.gallery.images
ここで定義しなくても必要な箇所で`@product`から取得すれば良いと思います。

2021-07-21 11:53 UTC, shimizu-yuta commented on app/helpers/application_helper.rb
> +    base_title = "BIGBAG Store"
定数は `UPPER_SNAKE_CASE`で定義しましょう。

2021-07-21 11:53 UTC, shimizu-yuta commented on app/views/layouts/_footer.html.erb
> +</div>
こちら不要です。

2021-07-21 11:53 UTC, shimizu-yuta commented on app/views/potepan/sample/products.html.erb
> +            <h3><%= @product.display_price.to_html %></h3>
`to_html`残っています

2021-07-21 11:53 UTC, shimizu-yuta commented on spec/features/products_spec.rb
> +    visit potepan_product_url(id: product.id)
visitは毎回呼ばれると思うので、最初にまとめて呼びましょう。

2021-07-21 11:53 UTC, shimizu-yuta commented on spec/features/products_spec.rb
> +    product = create(:product)
`let`で定義しましょう。

2021-07-21 11:53 UTC, shimizu-yuta commented on spec/helpers/application_helper_spec.rb
> +    end
endとitの間は1行あけましょう。

2021-07-22 00:41 UTC, youhei0204 commented
清水さん
川口です。丁寧なレビューありがとうございました。

2021-07-22 00:42 UTC, youhei0204 commented on spec/helpers/application_helper_spec.rb
> +    end
こちら修正しました。

2021-07-22 00:42 UTC, youhei0204 commented on spec/features/products_spec.rb
> +    product = create(:product)
こちら修正しました。

2021-07-22 00:42 UTC, youhei0204 commented on spec/features/products_spec.rb
> +    visit potepan_product_url(id: product.id)
こちら修正しました。

2021-07-22 00:42 UTC, youhei0204 commented on app/views/layouts/_footer.html.erb
> +</div>
こちら修正しました。

2021-07-22 00:42 UTC, youhei0204 commented on app/helpers/application_helper.rb
> +    base_title = "BIGBAG Store"
こちら修正しました。

2021-07-22 00:42 UTC, youhei0204 commented on app/controllers/potepan/products_controller.rb
> +      @images = @product.master.gallery.images
こちら修正しました。

2021-07-22 00:42 UTC, youhei0204 commented on app/controllers/potepan/products_controller.rb
> +      # issue#1
こちら修正しました。

2021-07-22 12:30 UTC, nakanoTaku commented on config/storage.yml
>    bucket: potepanec0yohei
`region`や`bucket`も環境変数から参照できるようにしましょう。

2021-07-22 12:39 UTC, nakanoTaku commented on spec/requests/sample_controller_spec.rb
> +      expect(response).to render_template :show
レスポンスコードの検証も追加しましょう。

2021-07-22 12:43 UTC, nakanoTaku commented
レビュアーの中野です。
インラインでコメントしましたので、ご確認お願いします。

2021-07-22 15:48 UTC, youhei0204 commented
中野さん
川口です。レビューありがとうございました。

2021-07-22 15:48 UTC, youhei0204 commented on spec/requests/sample_controller_spec.rb
> +      expect(response).to render_template :show
こちら追加しました。

2021-07-22 15:48 UTC, youhei0204 commented on config/storage.yml
>    bucket: potepanec0yohei
こちら修正しました。

2021-07-23 00:39 UTC, bary822 reviewed
レビュアーの福井です。テストに関して2点だけコメントしました。

また所感ですが、`rubocop --auto-correct`による差分と機能実装の差分が入り混じっているため非常にレビューしづらいです。
今回は許容しますが、実際の開発現場ではこのようなPull Requestがapproveされることはない点にご留意ください。
本来ならそれぞれ別のPull Requestとして出されるべきです。

2021-07-23 00:39 UTC, bary822 commented on spec/requests/products_controller_spec.rb
> +RSpec.describe Potepan::SampleController, type: :request do
`describe`に与えるクラス名を変更しましょうか。
Request SpecはController Specとは異なるものなので、これに与える文言の慣習も異なっています。
機能単位やテストしたい主題を与えるようにしてください。
https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec

2021-07-23 00:39 UTC, bary822 commented on spec/requests/products_controller_spec.rb
> +  describe "Get /potepan/products/:id" do
商品機能に関連したテストは別ファイルに切り出してください。

2021-07-23 05:40 UTC, youhei0204 commented on spec/requests/products_controller_spec.rb
> +RSpec.describe Potepan::SampleController, type: :request do
こちら修正しました。

2021-07-23 05:40 UTC, youhei0204 commented on spec/requests/products_controller_spec.rb
> +  describe "Get /potepan/products/:id" do
こちら修正しました。

2021-07-23 05:42 UTC, youhei0204 commented
福井さん
川口です。レビューありがとうございました。
rubocopのauto correctで差分ファイルが多くなってしまい、
確かに見辛いPRになってしまいました。お手数おかけしました。

2021-07-23 06:53 UTC, kaizumoto commented on .rspec
> +--format documentation
EOFがおかしくなっているので対応をお願いします。

2021-07-23 07:05 UTC, kaizumoto commented
レビュアーの伊豆本です。
インラインでコメントしましたのでご確認ください。

2021-07-23 08:02 UTC, youhei0204 commented
伊豆本さん
川口です。レビューありがとうございました。

2021-07-23 08:02 UTC, youhei0204 commented on .rspec
> +--format documentation
こちら修正しました。

2021-07-23 09:00 UTC, masanarih0ri commented on Gemfile
> +# gem 'solidus_auth_devise'
これってコメントアウトで残す必要はあるんですか？

2021-07-23 09:01 UTC, masanarih0ri commented on app/views/potepan/products/show.html.erb
> +
HTMLの空行はなくしましょう。他のファイルの確認もお願いします。

2021-07-23 10:16 UTC, masanarih0ri reviewed
お疲れ様です。少しコメントしました。

2021-07-23 11:17 UTC, youhei0204 commented on app/views/potepan/products/show.html.erb
> +
こちら修正しました。

2021-07-23 11:17 UTC, youhei0204 commented on Gemfile
> +# gem 'solidus_auth_devise'
こちら削除しました。

2021-07-23 13:23 UTC, nakanoTaku commented
レビュアーの中野です。
私は問題ないと思いますので、LGTMです。

2021-07-23 15:30 UTC, codethefuture reviewed
コメントしましたのでご確認ください。

2021-07-23 15:30 UTC, codethefuture commented on app/views/potepan/products/show.html.erb
> +                  <div class="item <%= 'active' if index == 0 %>" data-thumb="<%= index %>">
0との比較はメソッドがありますので、そちらを使いましょう。

2021-07-23 15:30 UTC, codethefuture commented on app/views/potepan/products/show.html.erb
> +<!-- LIGHT SECTION -->
若干このファイルの行数が長いようなので別パーシャルに切り出しましょう。

2021-07-23 15:30 UTC, codethefuture commented on spec/helpers/application_helper_spec.rb
> +    it "returns the default title if argument is blank" do
これ、1つにまとめるのではなくて、それぞれが別れていたほうがいいですね。

2021-07-24 00:37 UTC, youhei0204 commented on app/views/potepan/products/show.html.erb
> +                  <div class="item <%= 'active' if index == 0 %>" data-thumb="<%= index %>">
こちら修正しました。

2021-07-24 00:37 UTC, youhei0204 commented on app/views/potepan/products/show.html.erb
> +<!-- LIGHT SECTION -->
こちら修正しました。

2021-07-24 00:38 UTC, youhei0204 commented on spec/helpers/application_helper_spec.rb
> +    it "returns the default title if argument is blank" do
川口です。レビューありがとうございました。

2021-07-24 01:13 UTC, smatsumura-cq requested changes
レビュアーの松村です。
コメントしましたのでご確認ください。

rubocopで出た不要な差分は元に戻しましょう。

2021-07-24 01:13 UTC, smatsumura-cq commented on Rakefile
> +
このような差分は今回のPRとは関係ないので、戻してください。
差分ファイルが106ありますが、課題2では40前後におさまるはずなので、他の不要な差分も戻しましょう。

2021-07-24 01:13 UTC, smatsumura-cq commented on app/helpers/application_helper.rb
> +  BASE_TITLE = "BIGBAG Store"
定数はfreezeしましょう。

2021-07-24 01:13 UTC, smatsumura-cq commented on app/views/layouts/_header.html.erb
> +                  class="fa fa-search"></i></a>
iタグの改行位置が不自然ですね。。

2021-07-24 01:13 UTC, smatsumura-cq commented on app/views/potepan/products/_related_products.html.erb
> +<div class="row productsContent">
全体的にインデントずれてます。

2021-07-24 01:13 UTC, smatsumura-cq commented on spec/requests/products_controller_spec.rb
> +      expect(response).to render_template :show
requestではrender_templateは不要なので削除して良いです。

2021-07-24 01:31 UTC, youhei0204 commented on app/views/potepan/products/_related_products.html.erb
> +<div class="row productsContent">
レビューありがとうございます。こちら、とくにズレていないように見えるのですが、
行をご指摘いただけると助かります。

2021-07-24 03:47 UTC, youhei0204 commented on app/helpers/application_helper.rb
> +  BASE_TITLE = "BIGBAG Store"
コメントありがとうございます。
こちら、L.1の# frozen_string_literal: true で実現しています。

2021-07-24 04:26 UTC, youhei0204 commented on spec/requests/products_controller_spec.rb
> +      expect(response).to render_template :show
こちら修正しました。

2021-07-24 04:26 UTC, youhei0204 commented on app/views/potepan/products/_related_products.html.erb
> +<div class="row productsContent">
こちら修正しました。

2021-07-24 04:48 UTC, masanarih0ri commented on app/views/layouts/application.html.erb
> +      <!-- HEADER -->
細かいんですが、partialの命名から、このコメント要らないと思いました。

2021-07-24 04:48 UTC, masanarih0ri commented on app/views/layouts/application.html.erb
> +      <!-- FOOTER -->
こちらも同様です。

2021-07-24 04:49 UTC, masanarih0ri commented on app/views/layouts/application.html.erb
> +    <!-- LOGIN MODAL -->
ここもですね。こういうコメントって命名がきちんとしていれば要らないことがほとんどだと思います。

2021-07-24 04:52 UTC, youhei0204 commented on app/views/layouts/application.html.erb
> +    <!-- LOGIN MODAL -->
ありがとうございます。勉強になります。

2021-07-24 05:06 UTC, youhei0204 commented on app/views/layouts/application.html.erb
> +      <!-- FOOTER -->
こちら修正しました。

2021-07-24 05:06 UTC, youhei0204 commented on app/views/layouts/application.html.erb
> +      <!-- HEADER -->
こちら修正しました。

2021-07-24 05:30 UTC, masanarih0ri reviewed
お疲れ様です。少しコメントしました。

2021-07-24 06:07 UTC, youhei0204 commented
レビューありがとうございます。
いただいたコメントを元に修正しました。

2021-07-24 10:24 UTC, kaizumoto commented on app/views/potepan/products/_light_section.html.erb
> +          <h2><%= @product.name %></h2>
partialからインスタンス変数にアクセスしないようにしましょう。

2021-07-24 10:26 UTC, kaizumoto commented on app/controllers/potepan/sample_controller.rb
> +  def products
このアクションは使用されていますか？

2021-07-24 10:28 UTC, kaizumoto commented
レビュアーの伊豆本です。
インラインでコメントしましたのでご確認ください。

2021-07-24 13:17 UTC, youhei0204 commented on app/views/potepan/products/_light_section.html.erb
> +          <h2><%= @product.name %></h2>
ありがとうございます。勉強になりました。

2021-07-24 13:17 UTC, youhei0204 commented
伊豆本さん
川口です。レビューありがとうございました。

2021-07-25 01:09 UTC, shungo0525 requested changes
レビュアーの松村です。
数点コメントしました。

あともう少しです。

2021-07-25 01:09 UTC, shungo0525 commented on .rubocop.yml
> +
改行多いですね。

2021-07-25 01:09 UTC, shungo0525 commented on .rubocop.yml
> +
こちらも

2021-07-25 01:09 UTC, shungo0525 commented on app/controllers/potepan/products_controller.rb
> +  class ProductsController < ApplicationController
`class Potepam::ProductsController < ApplicationController`
の方が良いと思います。

2021-07-25 01:09 UTC, shungo0525 commented on config/routes.rb
> +    resources :products, :only => :show
`only: :show`の方がよく使われます

2021-07-25 01:09 UTC, shungo0525 commented on spec/requests/products_controller_spec.rb
> +      expect(response).to have_http_status 200
response.bodyにproductの情報が含まれることも確認しましょう。

2021-07-25 01:46 UTC, youhei0204 commented on .rubocop.yml
> +
こちら修正しました。

2021-07-25 01:46 UTC, youhei0204 commented on .rubocop.yml
> +
こちらも併せて修正しました。

2021-07-25 01:46 UTC, youhei0204 commented on app/controllers/potepan/products_controller.rb
> +  class ProductsController < ApplicationController
こちら修正しました。

2021-07-25 01:46 UTC, youhei0204 commented on config/routes.rb
> +    resources :products, :only => :show
ありがとうございます。勉強になります。

2021-07-25 01:46 UTC, youhei0204 commented on spec/requests/products_controller_spec.rb
> +      expect(response).to have_http_status 200
こちら追記しました。

2021-07-25 01:50 UTC, youhei0204 commented
松村さん
川口です。レビューありがとうございました。

2021-07-25 02:51 UTC, shungo0525 approved these changes
レビュアーの松村です。

私からはLGTMです。
次のレビュアーからのコメントをお待ちください。

2021-07-25 06:31 UTC, codethefuture approved these changes
LGTM!!!!

2021-07-25 07:32 UTC, merged

2021-07-25 07:33 UTC, youhei0204 commented
漸く課題2が完了しました。。
見ていただいた皆様、ありがとうございました。